name: "CICD FOR CPET"

on:
  push:
    branches: ["master"]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: test site
        run: |
          npm install
        env:
          CI: true

  deploy:
    timeout-minutes: 10
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: connect to SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          sshpass -p ${{secrets.SSH_PASSWORD}} 
          ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} 'whoami && cd ./CPET && npm install --force && sudo rm -rf /var/www/cpet.dhiu.in/html/* && sudo cp -r /home/ubuntu/CPET/client/build/* /var/www/cpet.dhiu.in/html && pm2 reload server.js && sudo nginx -t && sudo systemctl restart nginx && sudo systemctl reload nginx'
