name: CICD FOR CPET

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Test site
        run: npm install
        env:
          CI: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Connect to SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            whoami
            cd ./CPET
            git pull
            npm install
            pm2 reload server.js
            sudo nginx -t
